name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md" --exclude ".gitignore"
        env:
          AWS_S3_BUCKET: poojithreddy-portfolio
          AWS_ACCESS_KEY_ID: AKIA4JN3ZOWRFZIYD3PQ
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: us-east-1
